{
  "openapi": "3.0.0",
  "info": {
    "title": "Banking API Documentation",
    "description": "created by **Nazla Dio Hevin**\n\n@nazlahevin",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "User",
      "description": "Access user"
    },
    {
      "name": "Auth"
    },
    {
      "name": "Account"
    },
    {
      "name": "Transaction"
    },
    {
      "name": "Profile",
      "description": "get detatil for user"
    }
  ],
  "paths": {
    "/api/v1/users/20/profile": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "get user by id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "profile": {
                    "id": 7,
                    "userId": 20,
                    "identityType": "ktp",
                    "identityNumber": "3543434343",
                    "address": null,
                    "avatarUrl": "https://ik.imagekit.io/dztvhjdtp/akujgmw_Z6jo1CFLv.jpg",
                    "avatarId": "672d2365e375273f60301cc3",
                    "avatarName": "akujgmw_Z6jo1CFLv.jpg",
                    "createdAt": "2024-11-07T20:28:52.097Z",
                    "updateAt": "2024-11-07T20:30:20.206Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "User ID not found!"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "get all users",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 1,
                    "email": "stefford@gmail.com",
                    "name": "Stepuniues",
                    "password": "$2b$10$eLeWH3fHm1OjL2KsS44uEei.Ka1snyIszkcpzPcIYHFuAM2cMu1HO",
                    "createdAt": "2024-10-18T13:02:03.016Z",
                    "updateAt": "2024-10-29T10:54:21.898Z"
                  },
                  {
                    "id": 17,
                    "email": "nobita@gmail.com",
                    "name": "Nobita Nobi",
                    "password": "$2b$10$eLeWH3fHm1OjL2KsS44uEei.Ka1snyIszkcpzPcIYHFuAM2cMu1HO",
                    "createdAt": "2024-10-29T13:36:27.709Z",
                    "updateAt": null
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/users/18": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "update user",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Djenggot"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success",
                  "data": {
                    "id": 18,
                    "email": "naruto@gmail.com",
                    "name": "Djenggot",
                    "password": "$2b$10$xY0Zs4ObkY2Hsvs8UW1/MOVr/jm2LwY0by1lXWrxkjmSSUcfDsMvy",
                    "createdAt": "2024-10-29T17:35:59.435Z",
                    "updateAt": "2024-10-29T18:09:58.880Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "register",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Madara Uciha"
                  },
                  "password": {
                    "type": "integer",
                    "example": "123456"
                  },
                  "email": {
                    "type": "string",
                    "example": "madara@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success",
                  "data": {
                    "id": 20,
                    "email": "sasuke@gmail.com",
                    "name": "Uchiha Sasuke",
                    "password": "$2b$10$UBGiohvZwvbyyGzDGreyte346Zu/lue4cohnlo8jZeZ2CUtWHkFSC",
                    "createdAt": "2024-10-29T17:39:57.576Z",
                    "updateAt": null
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Email already use"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "login",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "nobita@gmail.com"
                  },
                  "password": {
                    "type": "integer",
                    "example": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Success login",
                  "data": {
                    "id": 17,
                    "email": "nobita@gmail.com",
                    "name": "Nobita Nobi",
                    "password": "$2b$10$eLeWH3fHm1OjL2KsS44uEei.Ka1snyIszkcpzPcIYHFuAM2cMu1HO",
                    "createdAt": "2024-10-29T13:36:27.709Z",
                    "updateAt": null,
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImlhdCI6MTczMDIyMzk0NCwiZXhwIjoxNzMwNDgzMTQ0fQ.7LUQF6n_4PGUA55PrMeFFEa1YJ8gBaKi3Ajjolu87fE"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Invalid email or password"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts": {
      "get": {
        "tags": [
          "Account"
        ],
        "summary": "get all account",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 2,
                    "balance": "1020000",
                    "bankAccountNumber": "828323728",
                    "bankName": "bca",
                    "createdAt": "2024-10-18T13:44:12.473Z",
                    "updateAt": null,
                    "userId": 2,
                    "deleteAt": null
                  },
                  {
                    "id": 3,
                    "balance": "1200000",
                    "bankAccountNumber": "23232323244",
                    "bankName": "mandiri",
                    "createdAt": "2024-10-28T20:08:39.805Z",
                    "updateAt": null,
                    "userId": 2,
                    "deleteAt": null
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Account"
        ],
        "summary": "create account",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "properties": {
                  "userId": {
                    "type": "integer",
                    "example": "17"
                  },
                  "bankName": {
                    "type": "string",
                    "example": "bri"
                  },
                  "bankAccountNumber": {
                    "type": "integer",
                    "example": "8748374837438"
                  },
                  "balance": {
                    "type": "integer",
                    "example": "3400000"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success",
                  "data": {
                    "id": 4,
                    "balance": "3400000",
                    "bankAccountNumber": "8748374837438",
                    "bankName": "bri",
                    "createdAt": "2024-10-29T18:23:38.897Z",
                    "updateAt": null,
                    "userId": 17,
                    "deleteAt": null
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts/2": {
      "delete": {
        "tags": [
          "Account"
        ],
        "summary": "delete account",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Bank Account ID not found!"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts/3": {
      "get": {
        "tags": [
          "Account"
        ],
        "summary": "get account by id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 3,
                  "balance": "1200000",
                  "bankAccountNumber": "23232323244",
                  "bankName": "mandiri",
                  "createdAt": "2024-10-28T20:08:39.805Z",
                  "updateAt": null,
                  "userId": 2,
                  "deleteAt": null,
                  "user": {
                    "id": 2,
                    "email": "julius@gmail.com",
                    "name": "Julius Nova Crono",
                    "password": "123456",
                    "createdAt": "2024-10-18T13:18:45.268Z",
                    "updateAt": "2024-10-18T13:42:31.582Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Account ID not found!"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/transactions": {
      "post": {
        "tags": [
          "Transaction"
        ],
        "summary": "create transaction",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "properties": {
                  "sourceAccountId": {
                    "type": "integer",
                    "example": "3"
                  },
                  "destinationAccountId": {
                    "type": "integer",
                    "example": "4"
                  },
                  "amount": {
                    "type": "integer",
                    "example": "120000"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Source Account ID not found"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "get all transactions",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 1,
                    "amount": "10000",
                    "createdAt": "2024-10-18T13:46:22.434Z",
                    "destinationAccountId": 2,
                    "sourceAccountId": 1,
                    "updateAt": null
                  },
                  {
                    "id": 2,
                    "amount": "10000",
                    "createdAt": "2024-10-28T19:44:05.919Z",
                    "destinationAccountId": 2,
                    "sourceAccountId": 1,
                    "updateAt": null
                  },
                  {
                    "id": 3,
                    "amount": "120000",
                    "createdAt": "2024-10-29T18:43:11.802Z",
                    "destinationAccountId": 4,
                    "sourceAccountId": 3,
                    "updateAt": null
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/transactions/3": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "get transaction by id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 3,
                    "amount": "120000",
                    "createdAt": "2024-10-29T18:43:11.802Z",
                    "destinationAccountId": 4,
                    "sourceAccountId": 3,
                    "updateAt": null,
                    "sourceAccount": {
                      "id": 3,
                      "balance": "1080000",
                      "bankAccountNumber": "23232323244",
                      "bankName": "mandiri",
                      "createdAt": "2024-10-28T20:08:39.805Z",
                      "updateAt": null,
                      "userId": 2,
                      "deleteAt": null
                    },
                    "destinationAccount": {
                      "id": 4,
                      "balance": "3520000",
                      "bankAccountNumber": "8748374837438",
                      "bankName": "bri",
                      "createdAt": "2024-10-29T18:23:38.897Z",
                      "updateAt": null,
                      "userId": 17,
                      "deleteAt": null
                    }
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Transaction ID not found!"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/15/profile": {
      "post": {
        "tags": [
          "Profile"
        ],
        "summary": "create profile",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary"
                  },
                  "identityType": {
                    "type": "string",
                    "example": "ktp"
                  },
                  "identityNumber": {
                    "type": "integer",
                    "example": "3543434343"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success",
                  "data": {
                    "id": 13,
                    "userId": 15,
                    "identityType": "ktp",
                    "identityNumber": "3543434343",
                    "address": null,
                    "avatarUrl": "https://ik.imagekit.io/dztvhjdtp/images_qwjdThX11.jpg",
                    "avatarId": "672f8e63e375273f601f7fc5",
                    "avatarName": "images_qwjdThX11.jpg",
                    "createdAt": "2024-11-09T16:31:26.133Z",
                    "updateAt": null
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Profile"
        ],
        "summary": "update profile",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary"
                  },
                  "identityNumber": {
                    "type": "integer",
                    "example": "82382382"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Profile updated successfully",
                  "profile": {
                    "id": 13,
                    "userId": 15,
                    "identityType": "ktp",
                    "identityNumber": "82382382",
                    "address": null,
                    "avatarUrl": "https://ik.imagekit.io/dztvhjdtp/avatar92_ayeEyHN6a.jpg",
                    "avatarId": "672f903be375273f60280f5c",
                    "avatarName": "avatar92_ayeEyHN6a.jpg",
                    "createdAt": "2024-11-09T16:31:26.133Z",
                    "updateAt": "2024-11-09T16:39:18.279Z"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "get profile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "profile": {
                    "id": 13,
                    "userId": 15,
                    "identityType": "ktp",
                    "identityNumber": "3543434343",
                    "address": null,
                    "avatarUrl": "https://ik.imagekit.io/dztvhjdtp/images_qwjdThX11.jpg",
                    "avatarId": "672f8e63e375273f601f7fc5",
                    "avatarName": "images_qwjdThX11.jpg",
                    "createdAt": "2024-11-09T16:31:26.133Z",
                    "updateAt": null
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/18/profile/avatar": {
      "delete": {
        "tags": [
          "Profile"
        ],
        "summary": "delete image avatar",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "success delete avatar",
                  "profile": {
                    "id": 7,
                    "userId": 20,
                    "identityType": "ktp",
                    "identityNumber": "3543434343",
                    "address": null,
                    "avatarUrl": null,
                    "avatarId": null,
                    "avatarName": null,
                    "createdAt": "2024-11-07T20:28:52.097Z",
                    "updateAt": "2024-11-09T16:37:02.248Z"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}